spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.238.101:5432/mydims
    url: jdbc:postgresql://192.168.137.128:5432/dims1
    username: postgres
    password: postgres
    tomcat:
      validation-query: select 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      max-active: 100
      min-idle: 5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null


