spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.137.101:5432/dims
      username: dims
      password: dims@123
    second:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.137.102:5432/dims-test
      username: dims
      password: dims@123
    tomcat:
      validation-query: select 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      max-active: 100
      min-idle: 5
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        primary-dialect: org.hibernate.dialect.PostgreSQL95Dialect
        second-dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart.max-file-size: 100MB
  flyway:
    enabled: true
    baseline-version: 8
    baseline-on-migrate: true
jenkins:
  url: http://192.168.137.101:8080/jenkins
  username: admin
  password: admin
template:
  datasource:
    username: dims
    password: dims@123
dims:
  url: http://192.168.137.1:10001
  license.key:
logging:
  level:
    root: info