spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.115.128:5432/dims1
      username: post
      password: post
    second:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.115.128:5432/quartz
      username: post
      password: post
    tomcat:
      validation-query: select 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      max-active: 100
      min-idle: 5
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        primary-dialect: org.hibernate.dialect.PostgreSQL95Dialect
        second-dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart.max-file-size: 100MB
  flyway:
    enabled: true
    baseline-version: 8
    baseline-on-migrate: true
jenkins:
  url: http://192.168.115.128:8080/jenkins/
  username: zhangyaox
  password: admin
template:
  datasource:
    username: pg
    password: pg
dims:
  url: http://172.22.84.46:10001
  license.key:
logging:
  level:
    root: info