server:
  port: 10001
  servlet:
    context-path: /
logging:
  file: dims.log
  level:
    root: info
# 设置指定配置文件生效：
# dev：指定application-dev.yml的配置文件生效
# pro：指定application-pro.yml的配置文件生效
spring:
  profiles:
    active: pro