spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dims
    username: admin
    password: lizhongnan
    tomcat:
      validation-query: select 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      max-active: 100
      min-idle: 5
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart.max-file-size: 100MB
  flyway:
    enabled: false
    baseline-version: 8
    baseline-on-migrate: true
server:
  port: 10001
  servlet:
    context-path: /
logging:
  file: dims.log
  level:
    root: info
jenkins:
  url: http://127.0.0.1:8080/jenkins
  username: whosyourdaddy
  password: -pl,ki8uhb
template:
  datasource:
    username: admin
    password: lizhongnan
dims:
  url: http://127.0.0.1:10000
  license.key:
