spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.238.101:5432/dims-420000-jk
    url: jdbc:postgresql://192.168.137.101:5432/dims
    username: dims
    password: dims@123
    tomcat:
      validation-query: select 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      max-active: 10
      min-idle: 5
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  batch:
    initialize-schema: never
    table-prefix: DIMS_BATCH_
    job:
      enabled: false
  flyway:
    enabled: true
    locations: classpath:\db\migration\special
logging:
  file: dims.log
  level:
    root: info
dims:
  url: http://localhost:10001


